### ISSUE TITLE
Probable typo in dfvfs/vfs/ntfs_file_entry.py

### ISSUE THREAD

**Issue by ant1** [log2timeline/dfvfs#115]
Line 362 of dfvfs/vfs/ntfs_file_entry.py,  there is:

362:      stat_object.atime_nan = stat_time_nano

This is probably a typo (atime_nan instead of atime_nano) ?

**Comment by joachimmetz** [comment]
Confirmed its a typo:

https://github.com/log2timeline/dfvfs/blob/f88c1ba8fbdea9ae0c2c941480a9599270b4bd76/dfvfs/vfs/ntfs_file_entry.py#L362

**Comment by joachimmetz** [comment]
Pending CL: http://codereview.appspot.com/283540043
