### ISSUE TITLE
Possible issue with _GetStat and *_nano in dfvfs/vfs/tsk_file_entry.py

### ISSUE THREAD

**Issue by ant1** [log2timeline/dfvfs#116]
Hi,

I'm using plaso 1.4.0,  dfvfs 20160108, sleuthkit 4.2.0, pytsk 20160111 on FreeBSD.

I noticed a 0 to 100 seconds shift between times given there and times given by fls (either Ubuntu 15.10 or FreeBSD) or plaso 1.3.0 on Ubuntu 15.10 (installed via apt-get from ubuntu repo).

If I understand correctly,  ```stat_object.*_nano``` are supposed to be in 100 nano seconds.
On FreeBSD with sleuthkit 4.2.0 and pytsk 20160111,  ```tsk_file.info.meta.*_nano``` are in nano seconds, not in  100 nano seconds so a conversion seems missing.

**Comment by ant1** [comment]
I may have found the origin of the bug,  if I diff sleuthkit 4.1.3 and 4.2.0:

```
--- sleuthkit-4.1.3/tsk/fs/ntfs.c       2014-01-27 03:27:03.000000000 +0000
+++ sleuthkit-4.2.0/tsk/fs/ntfs.c       2015-09-16 17:07:12.000000000 +0000
...
@@ -103,7 +104,7 @@ nt2unixtime(uint64_t ntdate)
 static uint32_t
 nt2nano(uint64_t ntdate)
 {
-    return (uint32_t) (ntdate % 10000000);
+    return (uint32_t) (ntdate % 10000000)*100;
 }


...
```

**Comment by joachimmetz** [comment]
There are ideas to switch to NTFS as the default. I'll need to see what change is the most appropriated.

**Comment by ant1** [comment]
Possible workaround:

```
--- dfvfs/vfs/tsk_file_entry.py.orig    2016-01-11 06:11:52 UTC
+++ dfvfs/vfs/tsk_file_entry.py
@@ -348,6 +348,20 @@ class TSKFileEntry(file_entry.FileEntry)
     stat_object.mtime_nano = getattr(
         tsk_file.info.meta, u'mtime_nano', None)
 
+    if pytsk3.TSK_VERSION_NUM >= 0x040200ff:
+      if stat_object.atime_nano is not None:
+        stat_object.atime_nano /= 100
+      if stat_object.bkup_time_nano is not None:
+        stat_object.bkup_time_nano /= 100
+      if stat_object.ctime_nano is not None:
+        stat_object.ctime_nano /= 100
+      if stat_object.crtime_nano is not None:
+        stat_object.crtime_nano /= 100
+      if stat_object.dtime_nano is not None:
+        stat_object.dtime_nano /= 100
+      if stat_object.mtime_nano is not None:
+        stat_object.mtime_nano /= 100
+
     # Ownership and permissions stat information.
     stat_object.mode = getattr(tsk_file.info.meta, u'mode', None)
     stat_object.uid = getattr(tsk_file.info.meta, u'uid', None)
```

And a regression test should be added,  as all the current pytsk/dfvfs/plaso tests were succeeding

**Comment by joachimmetz** [comment]
> And a regression test should be added, as all the current pytsk/dfvfs/plaso tests were succeeding

This will get address when stat interface is replaced with attributes interface https://github.com/log2timeline/dfvfs/issues/52

**Comment by joachimmetz** [comment]
A fix and test coverage are now in place. Note that the longer term idea is to deprecate the stat objects for a attributes that preserve the original precision.

**Comment by joachimmetz** [comment]
Closed this bug too early but last changes are now in.
