### ISSUE TITLE
Coveralls not working on Travis-CI

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfvfs#14]
After:

* packaging https://github.com/coagulant/coveralls-python and uploading to gift
* adding verbose output: https://github.com/log2timeline/dfvfs/commit/46ff9be43babed6562a0d4ffcf4a1466d4812c2c

```
Traceback (most recent call last):
  File "/usr/bin/coveralls", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3018, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 612, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 918, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 805, in resolve
pkg_resources.DistributionNotFound: requests>=1.0.0
```

Looks like we need add: https://pypi.python.org/pypi/requests
```
install_requires=['docopt>=0.6.1', 'coverage>=3.6', 'requests>=1.0.0'],
```

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/202210043

**Comment by kiddinn** [comment]
since I already added the CL I'm assigning this to me

**Comment by joachimmetz** [comment]
You can have it only if you update the package in gift as well ;)

**Comment by kiddinn** [comment]
then it's all yours ;)

**Comment by joachimmetz** [comment]
Pushed python-requests 1.2.3 to PPA

Still a couple of issues
```
dpkg: error processing /var/cache/apt/archives/python-coveralls_1.2.3-1ppa1~precise_all.deb (--unpack):
 trying to overwrite '/usr/lib/python2.7/dist-packages/requests/__init__.py', which is also in package python-requests 0.8.2-1
```

* need to force script to install from PPA
* why is coveralls shipping requests and than complaining it is missing it

**Comment by joachimmetz** [comment]
requests and coveralls fixed now coverage
```
pkg_resources.DistributionNotFound: coverage>=3.6
```

**Comment by joachimmetz** [comment]
Working now: https://coveralls.io/r/log2timeline/dfvfs?branch=master
