### ISSUE TITLE
python-dfvfs 20160428-1ppa1-xenial from PPA depends on libprotobuf[89] which are not available

### ISSUE THREAD

**Issue by NZC-2270116** [log2timeline/dfvfs#142]
This prevents installation of python-dfvfs from the ppa.

libprotobuf9v5 is available.

**Comment by NZC-2270116** [comment]
This is ppa:gift/dev

**Comment by NZC-2270116** [comment]
Seems that the dpkg deps generally need an update.  I manually installed python-cryptography and libprotobuf-dev.

**Comment by joachimmetz** [comment]
1. Per https://github.com/log2timeline/plaso/wiki/Ubuntu-Packaged-Release we only support Trusty, xenial is for development purposes only
2. Protobuf support is on the deprecation list: https://codereview.appspot.com/291570043/

> Seems that the dpkg deps generally need an update. I manually installed python-cryptography and libprotobuf-dev.

3. If you are volunteering to help out let me know
