### ISSUE TITLE
missing test_data\xedmynd.dd

### ISSUE THREAD

**Issue by randomaccess3** [log2timeline/dfvfs#147]
When running the test script I find it fails the final tests because it can't locate "test_data\xedmynd.dd"

**Comment by Onager** [comment]
Could you please provide some more information - what OS is this? How did
you install dfvfs?

**Comment by randomaccess3** [comment]
Win7 x64 running 32bit python (I ran 64bit python but the tests said the packages were out of date)

Ran a script I wrote (https://github.com/randomaccess3/4n6_stuff/blob/master/installDFVFS_0.02.pl) to download all of the packages and run the test so it's entirely possible that my script has does something but I had a look in the location and couldn't find the file it was after


======================================================================
ERROR: testOpenAndClose (vfs.tsk_file_system.TSKFileSystemTest)
Test the open and close functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\pmoore\Desktop\DFVFS\dfvfs\dfvfs-master\tests\vfs\tsk_file_system.py", line 30, in testOpenAndClose
    file_system.Open(self._tsk_path_spec)
  File ".\dfvfs\vfs\file_system.py", line 231, in Open
    self._Open(path_spec, mode=mode)
  File ".\dfvfs\vfs\tsk_file_system.py", line 64, in _Open
    path_spec.parent, resolver_context=self._resolver_context)
  File ".\dfvfs\resolver\resolver.py", line 119, in OpenFileObject
    file_object.open(path_spec=path_spec_object)
  File ".\dfvfs\file_io\file_io.py", line 73, in open
    self._Open(path_spec=path_spec, mode=mode)
  File ".\dfvfs\file_io\os_file_io.py", line 87, in _Open
    exception))
IOError: Unable to open file with error: [Error 2] The system cannot find the file specified: u'C:\\Users\\pmoore\\Desktop\\DFVFS\\dfvfs\\dfvfs-master\\test_data\\\xedmynd.dd'.

----------------------------------------------------------------------

**Comment by Onager** [comment]
This file has a non-ASCII character at the beginning ('í',
https://en.wikipedia.org/wiki/%C3%8D). Possibly this is the perl zip
library mangling the name. The archive looks fine to me - try unpacking it
with a different zip utility and seeing what happens.

**Comment by randomaccess3** [comment]
ah ok I see what's happened. the perl library is ignoring the file most probably due to the name
will have to figure out a way around this

thanks

**Comment by randomaccess3** [comment]
perl comes with version 1.47 of the extraction library, 1.57 fixes this issue

**Comment by randomaccess3** [comment]
Problem solved, was an error in the unzip library, code seems to be working now :)
