### ISSUE TITLE
Support for TAR files with missing directory entries.

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/dfvfs#148]
Sometimes programs will incorrectly create a tar file with the directory entries missing. When this happens, DFVFS does not correctly recognize these directories even though they could be inferred using the file path information found in the existing file entries.

I would like to add support for this.

**Comment by joachimmetz** [comment]
dfVFS uses the Python tar implementation. I'm not sure if what you want is easily done without rewriting it?

**Comment by dc3-plaso** [comment]
We can continue to use the builtin tar implementation and simply modify the TARDirectory class. I have a full implementation almost ready to be submitted.

**Comment by joachimmetz** [comment]
> We can continue to use the builtin tar implementation and simply modify the TARDirectory class.

OK then it's not entirely clear to me what you mean, but no need to explain the code changes will clear that up.

>  I have a full implementation almost ready to be submitted.

great, thanks.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfvfs/commit/a576e9aee17d549b568a621ac9e6610a6c493a63
