### ISSUE TITLE
Partition Disk

### ISSUE THREAD

**Issue by bobbypistol** [log2timeline/dfvfs#149]
Hey,

Is there a way to detect if an image has a partitiontable? We have different images where some contain a partitiontable and some are partition images (ie image start with NTFS header). 

```python
volume_path_spec = path_spec_factory.Factory.NewPathSpec(
    definitions.TYPE_INDICATOR_TSK_PARTITION, location=u'/',
    parent=path_spec)

    volume_system = tsk_volume_system(TSKVolumeSystem()
    volume_system.Open(volume_path_spec)
```

Depending on the image is throws an exception "Cannot determine partition type". Changing definitions between TYPE_INDICATOR_TSK and TYPE_INDICATOR_TSK_PARTITION seems to be working, but I couldn't find a way to automatically derive that information from the other objects

```python
os_path_spec = factory.Factory.NewPathSpec(
    definitions.TYPE_INDICATOR_OS, location=image_location)

type_indicator = analyzer.Analyzer.GetStorageMediaImageTypeIndicators(
    os_path_spec)

path_spec = factory.Factory.NewPathSpec(
    type_indicator[0], parent=os_path_spec)
```

I noticed that plaso can work with both type of images, I couldn't find where this detection is implemented :(

**Comment by joachimmetz** [comment]
Plaso uses the dfvfs SourceScanner to determine "disk layout"

https://github.com/log2timeline/plaso/blob/bd2327287cafed669ca78ab438c1665519f2f1e8/plaso/cli/storage_media_tool.py#L58

Also have a look at:

* https://github.com/log2timeline/dfvfs/wiki/Development
* https://github.com/log2timeline/dfvfs/blob/master/examples/recursive_hasher.py

**Comment by bobbypistol** [comment]
Wow thanks, works great! Only for some images the vss_store filesystem (not all, some) hangs and I have to kill the script. Not sure why

**Comment by joachimmetz** [comment]
Give it time to run opening old VSS can be expensive at the moment. Need to work on some performance improvements, when time permits.

**Comment by bobbypistol** [comment]
Additional question, in the HasherExample the volumes are exposed as a OpenFileEntry object with root as location and traversed recursively by a TSKFileObjects derived from the sub_file_entries. I tried defining a [new path_spec](https://github.com/log2timeline/dfvfs/wiki/Code-snippets ) with a specific location (ie. User Temp Directory) with the [base_path_spec](https://github.com/log2timeline/dfvfs/blob/master/examples/recursive_hasher.py#L471) as parent but that does not seem to work.
Changing the location of the base_path_spec seems to work but not sure what the right way is with DFVFS to access a file or directory directly and have them accessible as a Object.

**Comment by joachimmetz** [comment]
Can you add or link to the relevant part your code?

**Comment by bobbypistol** [comment]
```python
mediator = mount.VolumeScannerMediator()
volume_context = volume_scanner.VolumeScanner(mediator = mediator)
 try:
    base_path_specs = recursive_hasher.GetBasePathSpecs(options.source)
    if not base_path_specs:
      return False

  except KeyboardInterrupt:
    return_value = False
```
I merged some of the code to make it more clear.
```python
for base_path_spec in base_path_specs:
  file_system = resolver.Resolver.OpenFileSystem(base_path_spec)
  file_entry = resolver.Resolver.OpenFileEntry(base_path_spec)

  # Opening a path_spec with base_path_spec as parent does not seem to work
  tsk_path_spec = factory.Factory.NewPathSpec(
             definitions.TYPE_INDICATOR_TSK, location=u'/Users, 
             parent=base_path_spec)

  # Changing the location of base_path_spec seems to work
  base_path_spec.location = u'/Users'

  file_entry = resolver.Resolver.OpenFileEntry(tsk_path_spec)

```

**Comment by joachimmetz** [comment]
can you `print(base_path_spec.type_indicator)` before `tsk_path_spec = ...`

I think base_path_spec is already of type TSK meaning you are stacking a TSK path on top of a TSK path try `parent=base_path_spec.parent`. Seeing it is a path spec on the same level.

**Comment by bobbypistol** [comment]
Ah you are right. I have a follow up question tho. The base_path_specs variable contains all the base_path_specs for the partition/vss stores and seems te be working for all images (no None types). However looping through the base_path_specs gives me some problems. Following code:

```python
for base_path_spec in base_path_specs:
    tsk_path_spec = factory.Factory.NewPathSpec(
                                   definitions.TYPE_INDICATOR_TSK,
                                   location=u'/', #Could be any location (ie u'/Users/')
                                   parent=base_path_spec.parent)
    file_entry = resolver.Resolver.OpenFileEntry(
                           tsk_path_spec)
    for sub_file in file_entry.sub_file_entries:
        print sub_file.name
```

the loop stops unexpectedly without generating errors. If I run the loop without the "file_entry" function the output is as following:

```python
<dfvfs.path.tsk_path_spec.TSKPathSpec object at 0x7f501ca79b90>
TSK_PARTITION
<dfvfs.path.tsk_path_spec.TSKPathSpec object at 0x7f501ca79c90>
TSK_PARTITION
<dfvfs.path.tsk_path_spec.TSKPathSpec object at 0x7f501ca79dd0>
TSK_PARTITION
[dev@localhost]
```
However running with the file_entry function and printing the file entries, some images (not all) the loop stops unexpectedly and doesn't even print all the base_path_specs in the list (see block below). I tried putting the whole block in a try,except block but no difference. For some images it prints the file names as expected. 

```python
<dfvfs.path.tsk_path_spec.TSKPathSpec object at 0x7f501ca79b90>
TSK_PARTITION
#Loop stops here
[dev@localhost]
```
I tried disabling to parse VSS stores but it didn't solve the issue. The strange thing is that it doesn't happen for all images (roughly 50%) and I can read all information from the parent base_path_specs (ie volume offsets etc) so the base_path_specs seems valid. I'm using dfvfs version 20160514 but tried  different versions with the same result. Should I acquire base_path_specs for partitions and vss stores in another way then the RecursiveHasher example as log2timeline seems to be working fine? Sorry I can't provide any debugging information as there are no real errors.

**Comment by joachimmetz** [comment]
> The base_path_specs variable contains all the base_path_specs for the partition/vss stores and seems te be working for all images (no None types). 

Not partitions, but confirmed supported file systems.

so base_path can be a file system unsupported by TSK.

What does the output of https://github.com/log2timeline/dfvfs/blob/master/examples/source_analyzer.py look like on the same image?

**Comment by bobbypistol** [comment]
```python
Source type             : storage media image

OS: location: /path/to/image/image.E01
  EWF: 
    TSK_PARTITION: location: /
      TSK_PARTITION: 0, start offset: 0 (0x00000000)
        TSK: location: /
      TSK_PARTITION: 1, start offset: 0 (0x00000000)
        TSK: location: /
      TSK_PARTITION: 2, start offset: 1048576 (0x00100000), location: /p1
        TSK: location: /
      TSK_PARTITION: 3, start offset: 13959692288 (0x340100000), location: /p2
        TSK: location: /
      TSK_PARTITION: 4, start offset: 14064549888 (0x346500000), location: /p3
        VSHADOW: location: /
          VSHADOW: 0, location: /vss1
            TSK: location: /
          VSHADOW: 1, location: /vss2
            TSK: location: /
          VSHADOW: 2, location: /vss3
            TSK: location: /
          VSHADOW: 3, location: /vss4
            TSK: location: /
          VSHADOW: 4, location: /vss5
            TSK: location: /
          VSHADOW: 5, location: /vss6
            TSK: location: /
        TSK: location: /
      TSK_PARTITION: 5, start offset: 320071532544 (0x4a85c00000)

Completed.

```
partition 3 & 4 are mountable with ewfmount etc as they are normal NTFS partitions. 
mmls output

```
      Slot      Start        End          Length       Description
000:  Meta      0000000000   0000000000   0000000001   Primary Table (#0)
001:  -------   0000000000   0000002047   0000002048   Unallocated
002:  000:000   0000002048   0027265023   0027262976   Unknown Type (0x27)
003:  000:001   0027265024   0027469823   0000204800   NTFS / exFAT (0x07)
004:  000:002   0027469824   0625139711   0597669888   NTFS / exFAT (0x07)
005:  -------   0625139712   0625142447   0000002736   Unallocated

```

**Comment by joachimmetz** [comment]
Is this the output of one of the images that fails?

> However running with the file_entry function and printing the file entries, some images (not all) the loop stops unexpectedly and doesn't even print all the base_path_specs in the list (see block below). 

What is the value of `print(len(base_path_specs))` in these cases?

> partition 3 & 4 are mountable with ewfmount

Not sure if I understand what you're telling me, since ewfmount mounts EWF files as RAW data.

**Comment by bobbypistol** [comment]
> Is this the output of one of the images that fails?

Yes

> What is the value of print(len(base_path_specs)) in these cases?

3 (9 with VSS enabled)

> Not sure if I understand what you're telling me, since ewfmount mounts EWF files as RAW data.

I maybe suspected that the image was corrupt but works with the other tools.

**Comment by bobbypistol** [comment]
Small update, I kinda found out why why it wasn't working but i'm not sure why. After obtaining the  `base_path_specs = recursive_hasher.GetBasePathSpecs(options.source)` I looped through the base_path_specs and put each base_path_spec in a dictionary as I wanted to add additional information. 

```python
mounts = []
#Put each base_path_spec in seperate dict and add them to the list
if base_path_specs:
    for base_path_spec in base_path_specs:
        volume = {}
        volume.update('BasePathSpec' : base_path_spec})
        volume.update('OutPutFolder' :output_folder})
        mounts.append(volume)
return mounts
```
```python
volumes = [{'BasePathSpec': 'base_path_spec', 'OutputFolder': 'base_location'},
           {'BasePathSpec': 'base_path_spec', 'OutputFolder': 'base_location'} ,
           {'BasePathSpec': 'base_path_spec', 'OutputFolder': 'base_location'}]
```
```python
for entry in mounts:
    base_path_spec = entry['BasePathSpec']
    tsk_path_spec = factory.Factory.NewPathSpec(
        definitions.TYPE_INDICATOR_TSK,
        location=u'/Users',
        parent=base_path_spec.parent)
    file_entry = resolver.Resolver.OpenFileEntry(
       tsk_path_spec)
```

However looping through the dictionary and fetch each BasePathSpec value resulted in the errors above. 

Looping through the base_path_specs without putting them in a seperate dictionary first is working as intended (ie. I can loop through the desired folders and everything is working).

**Comment by bobbypistol** [comment]
Apparently there is a monitor in this project that kills a module if it doesn't generate output for a couple of seconds (debugging purposes), so yeah no shit there were no errors and  unexpected loop stops. Thanks for all the help and DfVFS works great, i'm just gonna cry in this corner and kill myself :) FML

**Comment by joachimmetz** [comment]
Thanks for the resolution, can you mention which project this entails, in case other people run into the same issue.
