### ISSUE TITLE
Create a MFT parser

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/dfvfs#17]
Need to have an independent MFT parser that can be used to parse extracted $MFT file.

Several options available, including using analyzeMFT as a library and import it.

**Comment by kiddinn** [comment]
and close this, since I'm again opening up in the wrong part, this was supposed to be opened in the plaso project, not dfVFS

**Comment by joachimmetz** [comment]
To be verbose, since an MFT by itself is not sufficient to parse the file system this functionality would only make sense in plaso as a "file format" parser.
