### ISSUE TITLE
Weird bug while handling a RAW split image

### ISSUE THREAD

**Issue by mkorman90** [log2timeline/dfvfs#178]
Hi, I have a really weird bug when handling a split raw image:
```
Attribute Run Dump:
  0 to 0 NotFiller
Traceback (most recent call last):
  File "dfvfs_tesing.py", line 135, in <module>
    recurse_over_file_entry(file_entry, volume_identifier=volume_identifier)
  File "dfvfs_tesing.py", line 19, in recurse_over_file_entry
    for sub_file_entry in file_entry.sub_file_entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/tsk_file_entry.py", line 446, in sub_file_entries
    for path_spec in self._directory.entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_entry.py", line 68, in entries
    for entry in self._EntriesGenerator():
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/tsk_file_entry.py", line 84, in _EntriesGenerator
    tsk_directory = fs_info.open_dir(path=location)
IOError: Directory_Con: (tsk3.c:361) Unable to open directory: General file system error (fs_attr_add_run: error adding additional run (58884): No filler entry for 0. Final: 1) (  - proc_attrseq: put run - proc_attrlist)
```

The weird thing is, if I go to /usr/lib/python2.7/dist-packages/dfvfs/vfs/tsk_file_entry.py, and change the line
` tsk_directory = fs_info.open_dir(path=location)`
to

try:
     tsk_directory = fs_info.open_dir(path=location)
except OSError:
     tsk_directory = fs_info.open_dir(path=location)

Everything works perfectly.

The image file I'm using is 100% valid, and works perfectly with other tools...
This reproduces in both python2.7 and python3.5

dfvfs version:
In [3]: dfvfs.__version__
Out[3]: '20160918'

Help is appreciated,
Martin.

**Comment by joachimmetz** [comment]
Thanks for reporting. Alas I did not see this issue earlier. I'll have a look if I can reproduce this when time permits.

**Comment by joachimmetz** [comment]
For some reason the trace back and the version of the code do not match:
https://github.com/log2timeline/dfvfs/blob/20160918/dfvfs/vfs/tsk_file_entry.py#L84

Also which version of pytsk / libtsk are you using?

**Comment by joachimmetz** [comment]
No update from reporter, unable to determine root cause.
