### ISSUE TITLE
Migrate from pycrypto to cryptography.io

### ISSUE THREAD

**Issue by Onager** [log2timeline/dfvfs#181]
Link: https://cryptography.io/en/latest/

**Comment by joachimmetz** [comment]
BTW we'll also need to make changes to l2tdevtools, l2tbinaries, and GIFT PPA.

**Comment by berggren** [comment]
And GIFTfF (GIFT for Fedora) :)
https://copr.fedorainfracloud.org/groups/g/gift/coprs/

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/l2tdevtools/issues/106

**Comment by joachimmetz** [comment]
https://github.com/pyca/cryptography comes with various dependencies.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/325310043

**Comment by joachimmetz** [comment]
RC4 only specific key sizes are supported
https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.algorithms.ARC4

**Comment by joachimmetz** [comment]
PyCrypto seems to be deprecated https://github.com/log2timeline/plaso/issues/2779
