### ISSUE TITLE
Support for ZIP files with missing directory entries

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/dfvfs#194]
There is a  bug similar to #148 where a zip file can be missing directory entries if created by Windows.

To reproduce this error,  I extracted the files in the syslog.zip file found in the test_data directory, placed the files in a folder named `folder` and then (in Windows 7) right clicked on the folder and used the 7z context menu to create `syslog_7z.zip` and the *"Sent To -> Compressed (zipped) folder"* menu to create `syslog_win.zip`.

Then running the following..

```python
#Necessary to prevent circular import.
from dfvfs import resolver

from dfvfs.path import zip_path_spec, os_path_spec
from dfvfs.vfs import zip_file_system
from dfvfs.resolver import context

for path in ['syslog_7z.zip', 'syslog_win.zip']:
  path_spec = os_path_spec.OSPathSpec(location=path)
  path_spec = zip_path_spec.ZipPathSpec(location'/', parent=path_spec)

  file_system = zip_file_system.ZipFileSystem(context.Context())
  file_system.Open(path_spec)

  file_entry = file_system.GetFileEntryByPathSpec(path_spec)
  
  print '==='
  print path_spec.comparable
  for sub_file_entry in file_entry.sub_file_entries:
    print sub_file_entry.path_spec.comparable
    for sub_sub_file_entry in sub_file_entry.sub_file_entries:
      print sub_sub_file_entry.path_spec.comparable
```
produces
```
===
type: OS, location: D:\syslog_7z.zip
type: ZIP, location: /

type: OS, location: D:\syslog_7z.zip
type: ZIP, location: /folder/

type: OS, location: D:\syslog_7z.zip
type: ZIP, location: /folder/syslog

type: OS, location: D:\syslog_7z.zip
type: ZIP, location: /folder/wtmp.1

===
type: OS, location: D:\syslog_win.zip
type: ZIP, location: /
```

As you can see, the it fails to find the files in the Windows version. 

The solution for #148 should also work for this.

**Comment by joachimmetz** [comment]
Changes merged in https://github.com/log2timeline/dfvfs/commit/19d9bb687ce1e615bd76c6c19479f969e71370cc

@dc3-plaso thanks for making the changes to fix this issue
