### ISSUE TITLE
Issue while reading image file

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/dfvfs#3]
While parsing the dblake win81 test image.

[chrome_cache] Unable to process file: 
 + type: OS, 
 + location: /<path>/test_images/win81_donald_blake/Donald_Blake_Evidence/C-Drive/YYYYMMDD-002-CDRIVE.E01
  + type: EWF
  + type: VSHADOW, 
  + store index: 2
    + type: TSK,
    + inode: 114275,
    + location: /Users/Donald/AppData/Local/Google/Chrome/User Data/Default/GPUCache/index

with error:
 + pyvshadow_store_read_buffer: unable to read data.
 + libvshadow_store_descriptor_read_buffer: unable to read buffer from file IO handle. 
 + libvshadow_internal_store_read_buffer_from_file_io_handle: unable to read buffer from store descriptor: 2. 
 + libvshadow_store_read_buffer: unable to read buffer from store descriptor: 2.

 + FS_Info_open: (tsk3.c:253) Unable to open file: 
 + Error reading image file (ntfs_dinode_lookup: 
 + Error reading MFT Entry at 3227558912).
```
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/plaso/engine/worker.py", line 123, in _ParseFileEntryWithParser
    parser_object.Parse(self._parser_context, file_entry)
  File "build/bdist.linux-x86_64/egg/plaso/parsers/chrome_cache.py", line 376, in Parse
    data_block_file_path_spec)
  File "build/bdist.linux-x86_64/egg/dfvfs/resolver/resolver.py", line 74, in OpenFileEntry
    return file_system.GetFileEntryByPathSpec(path_spec)
  File "build/bdist.linux-x86_64/egg/dfvfs/vfs/tsk_file_system.py", line 117, in GetFileEntryByPathSpec
    tsk_file = self._tsk_file_system.open(location)
RuntimeError: 'pyvshadow_store_read_buffer: unable to read data. libvshadow_store_descriptor_read_buffer: unable to read buffer from file IO handle. libvshadow_internal_store_read_buffer_from_file_io_handle: unable to read buffer from store descriptor: 2. libvshadow_store_read_buffer: unable to read buffer from store descriptor: 2.'
FS_Info_open: (tsk3.c:253) Unable to open file: Error reading image file (ntfs_dinode_lookup: Error reading MFT Entry at 3227558912)
```
The disk image can be shared upon request.

**Comment by joachimmetz** [comment]
Issue did not surface again in plaso 1.4 testing, closing issue.
