### ISSUE TITLE
Partition type

### ISSUE THREAD

**Issue by Mustachu** [log2timeline/dfvfs#305]
I'm currently working on a project which need extracting specific files depending on the OS.
I've looked on the way log2timeline finds the OS and it seems it does it by looking if some OS-specific folders exist (e.g /etc on Linux).
Is there any way to do this directly with dfvfs, for instance through the VolumeSystem ?

**Comment by joachimmetz** [comment]
> Is there any way to do this directly with dfvfs, for instance through the VolumeSystem ?

No, there is no guarantee that a volume of a specific type contains an OS.

**Comment by Mustachu** [comment]
Ok thanks, I guess I will have to do the same trick log2timeline does to check if there is an OS and what is its type.
