### ISSUE TITLE
Add check to see if file is open before closing

### ISSUE THREAD

**Issue by jnettesheim** [log2timeline/dfvfs#306]
In dfvfs/dfvfs/file_io/file_io.py, add check to confirm the file is currently open.  In Log2Timeline a conflict between dfwinreg and dfvfs leads to closing the same file twice.

**Comment by joachimmetz** [comment]
Related: https://github.com/log2timeline/dfvfs/issues/262

**Comment by joachimmetz** [comment]
@jnettesheim could you provide me some context around log2timeline/plaso@bafc477 this looks more related to #262 than an issue in combination with dfWinReg

**Comment by joachimmetz** [comment]
Removed the close in dfWinReg https://github.com/log2timeline/dfwinreg/pull/100

**Comment by joachimmetz** [comment]
Clean up for plaso: https://github.com/log2timeline/plaso/pull/2037

* needs updated version of dfWinReg

**Comment by joachimmetz** [comment]
Removed the need to explicitly call close https://github.com/log2timeline/dfvfs/pull/531
