### ISSUE TITLE
Add support for AWS S3

### ISSUE THREAD

**Issue by prats84** [log2timeline/dfvfs#308]
Add support to read disk images file from AWS S3 Buckets and use them as VFS

**Comment by joachimmetz** [comment]
@prats84 do you know if AWS S3 supports stat? I've seen some cloud file system implements not support this, if this is the case it would be hard to implement support into dfVFS for it.

**Comment by prats84** [comment]
If u mean stats messages, than yes. 
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectSELECTContent.html

**Comment by joachimmetz** [comment]
No update from original reporter and no priority, closing issue.
