### ISSUE TITLE
Investigate behavior for hybrid MBRs

### ISSUE THREAD

**Issue by Onager** [log2timeline/dfvfs#385]
Possibly a duplicate of #380 but there are user reports of problems where both an MBR and GPT are present.

**Comment by joachimmetz** [comment]
yes that is a duplicate, a work-around is to set vs type to TSK_VS_TYPE_GPT in
https://github.com/log2timeline/dfvfs/blob/master/dfvfs/vfs/tsk_partition_file_system.py#L68
