### ISSUE TITLE
Examples should not dump into the python generic examples folder

### ISSUE THREAD

**Issue by gregfreemyer** [log2timeline/dfvfs#4]
I just did a quick test of the 20121220 release and it has a couple examples in it.

Unfortunately they are being installed to:

/usr/lib/python2.7/site-packages/examples/init.py
/usr/lib/python2.7/site-packages/examples/init.pyc
/usr/lib/python2.7/site-packages/examples/recursive_hasher.py
/usr/lib/python2.7/site-packages/examples/recursive_hasher.pyc
/usr/lib/python2.7/site-packages/examples/recursive_hasher2.py
/usr/lib/python2.7/site-packages/examples/recursive_hasher2.pyc

They should go into a less generic examples folder.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/199870043/

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfvfs/commit/00f69557efb6bd43127577640d3aa0696a59be68
