### ISSUE TITLE
64 bit dependencies

### ISSUE THREAD

**Issue by jalwood** [log2timeline/dfvfs#40]
We're trying to transition to the 64 bit version of dfvfs.  When installing the 64 bit Windows dependencies on a test machine from https://github.com/log2timeline/l2tbinaries the check for the following modules fails with the following output

[FAILURE]       missing: pytsk3.
[FAILURE]       missing: pybde.
[FAILURE]       missing: pyewf.
[FAILURE]       missing: pyqcow.
[FAILURE]       missing: pysigscan.
[FAILURE]       missing: pysmdev.
[FAILURE]       missing: pysmraw.
[FAILURE]       missing: pyvhdi.
[FAILURE]       missing: pyvmdk.
[FAILURE]       missing: pyvshadow.

To follow up I opened a Python session to see if the modules could be imported.  construct, six, sqlite3, and dfvfs all import with no problems, all the modules listed above result in the following error:

>>> import pytsk3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.

The test machine is a 64 bit Windows 7 Pro.  To verify it wasn't an issue with the commit from 5 days ago I installed the 32 bit version of python and dependencies on a copy of the test image and had no similar problems running the tester or importing the modules.  If there is any other information you need I'd be happy to provide it.

**Comment by joachimmetz** [comment]
What is your 64-bit Python path?

**Comment by jalwood** [comment]
Default path of C:\Python27\

**Comment by joachimmetz** [comment]
> ImportError: DLL load failed: The specified module could not be found.

Possible causes:

* the DLL is not in C:\Python27\Libs\site-packages
* there is a 32-bit DLL in C:\Python27\Libs\site-packages

**Comment by jalwood** [comment]
The information about 32-bit DLLs possibly mucking up the works gave me the thought to check the DLL's in Dependency Walker and I found the problem, fresh Windows 7 installs are missing msvcr100.dll the 64 bit py libraries like libewf, libbde, etc need.  The 32 bit libraries require msvcr90.dll which is why we were not having issues with it.  After downloading the missing msvcr100.dll all the tests in run_tests.py ran successfully.  Thank you for your help!

**Comment by joachimmetz** [comment]
Thx for the feedback. I'll double check if this is in the installation instructions.

**Comment by joachimmetz** [comment]
Added a comment here: https://github.com/log2timeline/plaso/wiki/Windows-Packaged-Release closing issue.
