### ISSUE TITLE
How do I use DFVFS to view device paths?

### ISSUE THREAD

**Issue by xufuda** [log2timeline/dfvfs#407]
hey!
DFVFS is already dependent and automated, but how does parsing work?
Please give me a hand,thank you!
leo

**Comment by xufuda** [comment]
你好，这个项目是不是只提供接口呢？

**Comment by xufuda** [comment]
hello,this project only provides interfaces?

**Comment by joachimmetz** [comment]
@xufuda it is unclear to me what you are asking. dfVFS is not an end user tool, it's a Python module to provide read-only access to file-system objects from various storage media types and file formats.

Per README
```
The goal of dfVFS is to provide a generic interface for accessing file-system
objects, for which it uses several back-ends that provide the actual
implementation of the various storage media types, volume systems and file
systems.
```

**Comment by xufuda** [comment]
Your answer is exactly what I wanted to ask,so i need to use this module through python myself,right？

**Comment by joachimmetz** [comment]
Correct, see the following links for more information how to use dfVFS (these assume you know Python)

* https://github.com/log2timeline/dfvfs/wiki
* https://github.com/open-source-dfir/dfvfs-snippets
* https://github.com/open-source-dfir/dfvfs-snippets/wiki

**Comment by joachimmetz** [comment]
No update original reporter, considering question answered, closing issue
