### ISSUE TITLE
Is test_data/bdetogo.raw licensed under Apache-2.0?

### ISSUE THREAD

**Issue by hillu** [log2timeline/dfvfs#47]
I have been working to get plaso and its dependencies into Debian and was asked to check whether `test_data/bdetogo.raw` (or its contents) are actually licensed under the Apache-2.0 software license.

I did notice that, upon decryption using bdemount, there is a FAT image with some directories and seven files in it, four of which contain only zeroes. Am I missing something?

**Comment by joachimmetz** [comment]
>  (or its contents) are actually licensed under the Apache-2.0 software license.

Good question. I would need to check with someone that has more legal insight. The exes on the unencrypted part of the (locked) image are the default exes and mui DLLs BDE ToGo creates. I could shred their contents since we do not use it for the tests.

> Am I missing something?

Not sure which files you are referring to but the BDE ToGo images comes with a couple of files added for testing and a couple of files auto generated.

https://github.com/libyal/libbde/blob/master/documentation/BitLocker%20Drive%20Encryption%20(BDE)%20format.asciidoc#113-to-go

**Comment by hillu** [comment]
> Good question. I would need to check with someone that has more legal
> insight. The exes on the unencrypted part of the (locked) image are
> the default exes and mui DLLs BDE ToGo creates. I could shred their
> contents since we do not use it for the tests.

Ah, I wasn't aware that those volumes can be mounted as FAT
filesystems. So there is closed program code in there that clearly
does not fall unter Apache-2.0, even if it is only used as test data.

I am going to remove the test data from the Debian source package --
and disable the tests.

JFTR, I have pasted below what I did to inspect `bdetogo.raw`.
`bde-TEST` was the only password I found in the code.

Cheers,
-Hilko

<pre>
$ mkdir mnt mnt2
$ sudo bdemount -p bde-TEST bdetogo.raw mnt/
bdemount 20150204

$ sudo ls -la mnt
total 0
-r--r--r--. 1 root root 67108864 Jun  2  2014 bde1
$ sudo file mnt/bde1
mnt/bde1: DOS/MBR boot sector, code offset 0x3c+2, OEM-ID "mkdosfs", sectors/cluster 4, reserved sectors 4, root entries 512, Media descriptor 0xf8, sectors/FAT 128, sectors/track 56, heads 9, sectors 131072 (volumes > 32 MB) , serial number 0x54997bc, label: "           ", FAT (16 bit)
$ sudo mount mnt/bde1 mnt2
$ find mnt2 -type f -print0 | xargs -0 ls -l
-rwxr-xr-x. 1 root root      53 Jun  2  2014 mnt2/a_directory/a_file
-rwxr-xr-x. 1 root root      22 Jun  2  2014 mnt2/a_directory/another_file
-rwxr-xr-x. 1 root root     116 Jun  2  2014 mnt2/passwords.txt
-rwxr-xr-x. 1 root root 5331456 Jun  2  2014 mnt2/System Volume Information/FVE2.{24e6f0ae-6a00-4f73-984b-75ce9942852d}
-rwxr-xr-x. 1 root root   65536 Jun  2  2014 mnt2/System Volume Information/FVE2.{e40ad34d-dae9-4bc7-95bd-b16218c10f72}.1
-rwxr-xr-x. 1 root root   65536 Jun  2  2014 mnt2/System Volume Information/FVE2.{e40ad34d-dae9-4bc7-95bd-b16218c10f72}.2
-rwxr-xr-x. 1 root root   65536 Jun  2  2014 mnt2/System Volume Information/FVE2.{e40ad34d-dae9-4bc7-95bd-b16218c10f72}.3
$ cat mnt2/passwords.txt
place,user,password
bank,joesmith,superrich
alarm system,-,1234
treasure chest,-,1111
uber secret laire,admin,admin
$ cat mnt2/a_directory/a_file
This is a text file.

We should be able to parse it.
$ cat mnt2/a_directory/another_file
This is another file.
$ hd 'mnt2/System Volume Information/FVE2.{24e6f0ae-6a00-4f73-984b-75ce9942852d}'
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00515a00
$ hd 'mnt2/System Volume Information/FVE2.{e40ad34d-dae9-4bc7-95bd-b16218c10f72}.1'
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00010000
bengen@ataraxia:test_data $ hd 'mnt2/System Volume Information/FVE2.{e40ad34d-dae9-4bc7-95bd-b16218c10f72}.2'
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00010000
bengen@ataraxia:test_data $ hd 'mnt2/System Volume Information/FVE2.{e40ad34d-dae9-4bc7-95bd-b16218c10f72}.3'
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00010000
</pre>

**Comment by joachimmetz** [comment]
> bde-TEST was the only password I found in the code.

That's the correct one.

> mnt2/System Volume Information/FVE2.{24e6f0ae-6a00-4f73-984b-75ce9942852d}

It is correct that these appear to be 0-byte filled with bdemount. Also see:
https://github.com/libyal/libbde/blob/master/documentation/BitLocker%20Drive%20Encryption%20%28BDE%29%20format.asciidoc#11-metadata-files

These are BDE metadata files.

> So there is closed program code in there that clearly does not fall unter Apache-2.0, even if it is only used as test data.

In that case I'll shred the contents of these files, they are not needed for the test. IMO there is no need to distribute the test files beyond development at all, but I'll leave that up to you.

**Comment by hillu** [comment]
Since a Debian package for plaso is also sitting in the queue, please do the same there. Thank you.

**Comment by joachimmetz** [comment]
ack, that was implied on my side since it's the same file.

**Comment by joachimmetz** [comment]
zero-ed out the sectors of .exe.mui and .exe files
