### ISSUE TITLE
reconsider adding install_requires to setup.py

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfvfs#515]
Previously install_requires in setup.py caused more grief than benefit. See if things have matured.

**Comment by jpsnyder** [comment]
If you don't want the file system dependencies to be installed by default, I suggest at least including them as `extras_require` so one could install them with a command such as `pip install dfvfs[wiith_deps]`.

**Comment by joachimmetz** [comment]
this would require to make them optional dependencies as well, that is not really the goal here

**Comment by jpsnyder** [comment]
Gotcha. Well I support it. It would remove the need for me to manually include dfvfs's dependencies in my own project.

**Comment by joachimmetz** [comment]
>  It would remove the need for me to manually include dfvfs's dependencies in my own project.

for most regular uses of setup.py likely

but Python (pip and setup.py) dependency management has some gotchas and trade offs

**Comment by joachimmetz** [comment]
Contextual information:

* https://packaging.python.org/discussions/install-requires-vs-requirements/
* https://caremad.io/posts/2013/07/setup-vs-requirement/

**Comment by joachimmetz** [comment]
This required additional changes to prevent both rpm and dpkg configurations to ignore dependencies indicated by setup.py
