### ISSUE TITLE
Replace PyCrypto with PyCryptodome

### ISSUE THREAD

**Issue by rhertzog** [log2timeline/dfvfs#517]
FYI I'm forwarding this bug from Debian: https://bugs.debian.org/971311

dfvfs currently depends on PyCrypto. This project is no longer maintained and PyCryptodome (https://www.pycryptodome.org/en/latest/) provides a drop in replacement. Please switch to PyCryptodome.

**Comment by joachimmetz** [comment]
@rhertzog Debian needs to update their version of dfVFS, we migrated off PyCrypto beginning of this year https://github.com/log2timeline/dfvfs/commit/3ebccbdbe7c396f2cdfb735a325557842476e75c

**Comment by joachimmetz** [comment]
Related issue: https://github.com/log2timeline/dfvfs/issues/181
