### ISSUE TITLE
Failure during test: 'pytsk3.TSK_FS_INFO' object has no attribute 'ftype'

### ISSUE THREAD

**Issue by sbrun** [log2timeline/dfvfs#544]
Hello,

The package dfvfs fails to build in Debian during the tests with the error:
```
  File "./dfvfs/vfs/tsk_file_entry.py", line 454, in __init__
    self._file_system_type = tsk_file.info.fs_info.ftype
AttributeError: 'pytsk3.TSK_FS_INFO' object has no attribute 'ftype'
```
It has been reported in Debian (with full log):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971149

The dfvfs build fails in version 20190128 currently in Debian and also in more recent version 20211219.
I supposed it is related to pytsk (currently we have version 20200117 in Debian).
Thanks

**Comment by joachimmetz** [comment]
Yes this is pytsk/libtsk related what version of libtsk is pytsk generated from?

**Comment by joachimmetz** [comment]
Looks like libtsk still has a ftype member https://github.com/sleuthkit/sleuthkit/blob/develop/tsk/fs/tsk_fs.h#L969

**Comment by sbrun** [comment]
pytsk has been built with libtsk 4.10.1 (https://buildd.debian.org/status/fetch.php?pkg=pytsk&arch=amd64&ver=20200117-2%2Bb3&stamp=1611118544&raw=0)

**Comment by joachimmetz** [comment]
Would need to check, libtsk changed from 4.7 and 4.8 which has been breaking pytsk in several aspects.

**Comment by joachimmetz** [comment]
@sbrun does the Debian build system preserve pytsk3.c any where?

**Comment by joachimmetz** [comment]
Also why is this?
```
Depends: libafflib0v5 (>= 3.7.6), libc6 (>= 2.14), libewf2 (>= 20121209), libgcc-s1 (>= 3.0), libstdc++6 (>= 5.2), libtalloc2 (>= 2.0.4~git20101213), libvhdi1 (>= 20150110), libvmdk1 (>= 20150516), zlib1g (>= 1:1.1.4), python3 (<< 3.10), python3 (>= 3.9~)
```

libafflib0v5, libewf2, libvhdi1, libvmdk1, zlib1g are dependencies of libtsk not of pytsk

**Comment by joachimmetz** [comment]
@sbrun also anywhere where I could see the contents of:
```
Generating Python bindings for module pytsk3 from ['/usr/include/tsk/libtsk.h', '/usr/include/tsk/base/tsk_base.h', '/usr/include/tsk/fs/tsk_fs.h', '/usr/include/tsk/img/tsk_img.h', '/usr/include/tsk/vs/tsk_vs.h', 'tsk3.h']
```

In case Debian specific patches have been applied to libtsk

**Comment by sbrun** [comment]
For the contents of the files in /usr/include/tsk and the tsk3.h I attached the headers-tsk.zip. 
[headers-tsk.zip](https://github.com/log2timeline/dfvfs/files/5872106/headers-tsk.zip)
Or you can download the package libtsk-dev here (the .deb) for the include files:
https://packages.debian.org/sid/amd64/libtsk-dev/download

Debian patches applied to pytsk are here:
https://salsa.debian.org/pkg-security-team/pytsk/-/tree/debian/master/debian/patches

Debian patches applied to sleuthkit (libtsk) are here:
https://salsa.debian.org/pkg-security-team/sleuthkit/-/tree/debian/master/debian/patches

**Comment by sbrun** [comment]
> Also why is this?
> 
> ```
> Depends: libafflib0v5 (>= 3.7.6), libc6 (>= 2.14), libewf2 (>= 20121209), libgcc-s1 (>= 3.0), libstdc++6 (>= 5.2), libtalloc2 (>= 2.0.4~git20101213), libvhdi1 (>= 20150110), libvmdk1 (>= 20150516), zlib1g (>= 1:1.1.4), python3 (<< 3.10), python3 (>= 3.9~)
> ```
> 
> libafflib0v5, libewf2, libvhdi1, libvmdk1, zlib1g are dependencies of libtsk not of pytsk

This are auto-generated dependencies during the build: Debian links tsk statically in pytsk so we need these dependencies (see the patch applied to pytsk).

**Comment by joachimmetz** [comment]
@sbrun thx for the additional context, I'll have a look when time permits. If in the mean time you know where to get a hold of the  pytsk3.c file generated during build that could be useful.

**Comment by sbrun** [comment]
OK thanks.
I will build the package locally to generate the pytsk3.c file and attach it here.

**Comment by sbrun** [comment]
Here is the generated pytsk3.c:
[pytsk3.zip](https://github.com/log2timeline/dfvfs/files/5872341/pytsk3.zip)

**Comment by joachimmetz** [comment]
From a pytsk3.c of a libtsk 4.7 build:
```
Struct TSK_FS_INFO:
    int : tag
...
    uint64_t : journ_inum
    TSK_FS_TYPE_ENUM : ftype
    TSK_FS_INFO_FLAG_ENUM : flags
...
```

From the provided pytsk3.c
```
Struct TSK_FS_INFO:
    int : tag


    Enum TSK_FS_INFO_FLAG_ENUM:
    TSK_FS_INFO_FLAG_NONE
    TSK_FS_INFO_FLAG_HAVE_SEQ
    TSK_FS_INFO_FLAG_HAVE_NANOSEC
    TSK_FS_INFO_FLAG_ENCRYPTED

    Enum TSK_FS_ISTAT_FLAG_ENUM:
    TSK_FS_ISTAT_NONE
    TSK_FS_ISTAT_RUNLIST
```

So various fields are appear to be missing from the generate binding.

**Comment by joachimmetz** [comment]
From another pytsk3.c of a libtsk 4.10.1 build:
```
Struct TSK_FS_INFO:
    int : tag


    Enum TSK_FS_INFO_FLAG_ENUM:
    TSK_FS_INFO_FLAG_NONE
    TSK_FS_INFO_FLAG_HAVE_SEQ
    TSK_FS_INFO_FLAG_HAVE_NANOSEC
    TSK_FS_INFO_FLAG_ENCRYPTED

    Enum TSK_FS_ISTAT_FLAG_ENUM:
    TSK_FS_ISTAT_NONE
    TSK_FS_ISTAT_RUNLIST
```

So looks like this is an issue as of libtsk 4.8.0

**Comment by joachimmetz** [comment]
@sbrun I'll continue traking this issue in https://github.com/py4n6/pytsk/issues/71, seeing this is not a dfVFS issue but a pytsk/libtsk one
