### ISSUE TITLE
How to handle FileIO

### ISSUE THREAD

**Issue by jpsnyder** [log2timeline/dfvfs#567]
I'm currently updating a project that uses dfvfs (without plaso). I was previously using a version that is a couple years old.
Through the update process I noticed you deprecated the `close()` function for `FileIO` objects. https://github.com/log2timeline/dfvfs/pull/531

It seems now the only way to close a `FileIO` is through the private method `_Close()`, which I'm afraid will have unintended consequences. 

What is the new best practice for handling `FileIO` objects? Should they just be left open now? Below is a sample of my code used to open every file found in an image using `GetFileObject()` for processing.

```python
def _process_file_entry_data_stream(self, file_entry: FileEntry, data_stream_name: str):
    file_object = file_entry.GetFileObject(data_stream_name=data_stream_name)
    if not file_object:
        raise RuntimeError(f"Unable to retrieve file-like object for data stream: {data_stream_name}")
    try:
        result = self._callback(file_entry, file_object)
    finally:
        file_object.close()   # should I replace this with file_object._Close()  or just remove it?
```

**Comment by joachimmetz** [comment]
There is no need to close them any more, they are cached in the resolver context, which takes care of closing them. As you can see here https://github.com/log2timeline/dfvfs/blob/main/dfvfs/file_io/file_io.py#L27 `_Close()` is called when the object is de-referenced. The cache in the resolver context uses weak references which are not included in the reference counting.

If you need to support more than the default number of open file IO and system objects, you can create a custom resolver context https://github.com/log2timeline/dfvfs/blob/main/dfvfs/resolver/context.py#L11

> It seems now the only way to close a FileIO is through the private method _Close(), which I'm afraid will have unintended consequences.

Correct I don't recommend using the "private" or "protected" methods like `_Close()` directly

Hope this clarifies things

**Comment by jpsnyder** [comment]
Thanks. This was helpful. Looks like keeping the file open works. Appreciate the help.

**Comment by joachimmetz** [comment]
Just realize that if you open the same file IO object a second time from the same resolver context you'll get the same object. This will point at the offset where last read.

I'll close this issue, but feel free to reopen if more related questions surface.

**Comment by jpsnyder** [comment]
Right, I suspected that. Luckily I should only be opening each file once. But that is good to know.
