### ISSUE TITLE
Invalid extfs extents header signature raises IOError

### ISSUE THREAD

**Issue by dfjxs** [log2timeline/dfvfs#624]
An invalid extfs extents header signature causes a crash. We should instead handle the exception and continue.

**Comment by joachimmetz** [comment]
Regarding https://github.com/log2timeline/dfvfs/pull/625 I'm not in favor of this solution inside dfVFS, this will silently swallow a file system error, which IMHO is not good practice. It is best to do this in the calling code e.g. https://github.com/open-source-dfir/dfvfs-snippets/blob/main/scripts/recursive_hasher.py#L117

**Comment by dfjxs** [comment]
You're right, I wasn't catching the exception correctly. Closing the issue.

**Comment by joachimmetz** [comment]
https://github.com/libyal/libfsext/issues/7 to address underlying issue
