### ISSUE TITLE
Add modifier support

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/dfvfs#7]
Add a modular modifier support into dfVFS.

This would be a feature request for a way to indicate that the data should be manipulated/decoded in a certain way before being read, something like base64, ROT13, XOR with key "0xdd", etc. This could also expand to decryption support for file-level encryption.

First step, create the plugin framework, have that in dfVFS and implement something simple like base64 support.

* [x] ~~encoded stream path spec~~
* [x] ~~compressed file system support~~
* [x] ~~encoded file system support~~
* [x] ~~pycrypto - packaged release~~
  * ~~macosx~~
  * ~~ubuntu~~
  * ~~win32~~
  * ~~win64~~
* [x] ~~pycrypto - installation instructions~~
  * ~~fedora~~
  * ~~macosx~~
  * ~~ubuntu~~
  * ~~windows~~
* [x] ~~[encrypted stream support](https://codereview.appspot.com/281160043/)~~
* [x] fix https://launchpad.net/~gift/+archive/ubuntu/testing/+build/8916253

**Comment by joachimmetz** [comment]
I'll add:

* encoded stream path spec
* encrypted stream path spec (Pythonize libcaes instead of dragging in m2crypto or equiv)

**Comment by joachimmetz** [comment]
Initial version of the encoded stream support: http://codereview.appspot.com/198040043

After this I will move the "private" decoder classes into a more "plug-able" solution.

**Comment by joachimmetz** [comment]
Initial version of plug-able Decompressor and Decoder: https://codereview.appspot.com/199040043/

**Comment by joachimmetz** [comment]
To do:

* add compressed and encoded file system support

**Comment by joachimmetz** [comment]
compressed file system support: https://codereview.appspot.com/196310043/

**Comment by joachimmetz** [comment]
SQLite blob support: https://github.com/log2timeline/dfvfs/commit/fc470a066a667603b4406f9a202ccee28958fa6a

**Comment by joachimmetz** [comment]
Initial work on pycaes for AES encrypted stream support: https://github.com/libyal/libcaes/commit/68fa111fc2c033453ff26f35a63531e2a35b528a
