### ISSUE TITLE
pytsk import changes localtime globally in the environment

### ISSUE THREAD

**Issue by Rafiot** [log2timeline/dfvfs#721]
I discovered this issue because an other library that expects the local time to be correct was failing.

To reproduce simply do that:
```python

In [1]: import time

In [2]: print(time.localtime())
time.struct_time(tm_year=2023, tm_mon=4, tm_mday=4, tm_hour=18, tm_min=19, tm_sec=16, tm_wday=1, tm_yday=94, tm_isdst=1)

In [3]: from dfvfs.analyzer import analyzer

In [4]: print(time.localtime())
time.struct_time(tm_year=2023, tm_mon=4, tm_mday=4, tm_hour=16, tm_min=19, tm_sec=23, tm_wday=1, tm_yday=94, tm_isdst=0)

```

**Comment by joachimmetz** [comment]
this is related to a work around (in pytsk) for an issue in libtsk, see https://github.com/py4n6/pytsk/blob/1637f299aadc445c0a0aa58385848f01fe638868/tsk3.cpp#L702

**Comment by Rafiot** [comment]
Alright, I implemented a fix on my end. Not the prettiest piece of code, but it will do the trick.

**Comment by joachimmetz** [comment]
Yeah unfortunately this is the current situation. Getting anything structural changed in libtsk is very time consuming, but another reason to move away from it.
