### ISSUE TITLE
No such file: "cpio.yaml"

### ISSUE THREAD

**Issue by HoHunning** [log2timeline/dfvfs#751]
When I install latest dfvfs, my process show that
```
no such file or directory: '/usr/local/lib/python3.10/site-packages/dfvfs/lib/cpio.yaml'
```
And the problem gone after I change back to the older version. 
I guess something miss in latest one.

Best Regards

**Comment by rgayon** [comment]
+1

This is most likely a similar issue as in https://github.com/log2timeline/plaso/issues/1917

I fixed it by copying https://raw.githubusercontent.com/log2timeline/dfvfs/master/dfvfs/lib/cpio.yaml, and https://raw.githubusercontent.com/log2timeline/dfvfs/master/dfvfs/lib/gzipfile.yaml in the expected directory, such as  /usr/local/lib/python3.10/site-packages/dfvfs/lib/

**Comment by joachimmetz** [comment]
> And the problem gone after I change back to the older version.

this is an issue in the latest pre-release and has been addressed.
