### ISSUE TITLE
Improve file system support

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfvfs#82]
Improve file system support:
- [x] ~~Support for NTFS ADS~~
- [x] ~~add support for NTFS MFT attributes~~
- [x] ~~Support for HFS forks~~

**Comment by rgayon** [comment]
Support for XFS would also be nice to have.

**Comment by joachimmetz** [comment]
> Support for XFS would also be nice to have.

Created https://github.com/log2timeline/dfvfs/issues/354 for tracking

**Comment by joachimmetz** [comment]
Closing issue in favor of https://github.com/log2timeline/dfvfs/projects/2
